name: mi_card
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^1.3.0
  hexcolor: ^1.0.4
  firebase_core: "0.5.0"
  firebase_auth: "^0.18.0+1"
  modal_progress_hud: ^0.1.3
  cloud_firestore: "^0.14.0+2"
  fl_chart: ^0.11.1
  validators: ^2.0.1
  floating_bottom_navigation_bar: ^1.4.1
  page_transition: "^1.1.6"
  marquee_widget: ^0.8.0
  image_picker: ^0.6.7+9
  auto_size_text: ^2.1.0
#  marquee: ^1.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/no_rect.png
    - images/rect.png
    - images/PNG-FC-Signature Biru-Horisontal.png
    - images/PNG-FC-Signature Biru-Horisontal_ed.png
    - images/PNG-FC-Signature Biru-Tengah.png
    - images/PNG-FC-Signature Biru-Vertikal.png
    - images/Misaka_2.png
    - images/Card1.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Black_0.otf
        - asset: fonts/Montserrat-BlackItalic_0.otf
        - asset: fonts/Montserrat-Bold_0.otf
        - asset: fonts/Montserrat-BoldItalic_0.otf
        - asset: fonts/Montserrat-ExtraBold_0.otf
        - asset: fonts/Montserrat-ExtraBoldItalic_0.otf
        - asset: fonts/Montserrat-ExtraLight_0.otf
        - asset: fonts/Montserrat-ExtraLightItalic_0.otf
        - asset: fonts/Montserrat-Italic_0.otf
        - asset: fonts/Montserrat-Light_0.otf
        - asset: fonts/Montserrat-LightItalic_0.otf
        - asset: fonts/Montserrat-Medium_0.otf
        - asset: fonts/Montserrat-MediumItalic_0.otf
        - asset: fonts/Montserrat-Regular_0.otf
        - asset: fonts/Montserrat-SemiBold_0.otf
        - asset: fonts/Montserrat-SemiBoldItalic_0.otf
        - asset: fonts/Montserrat-Thin_0.otf
        - asset: fonts/Montserrat-ThinItalic_0.otf

